<a href="https://colab.research.google.com/github/fatimazain118/Cpp-basic-oops-STL-/blob/main/Assignment_2/1_mpgknn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [178]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Exploration and Visualization of MPG Data

In [179]:
from google.colab import drive              #mounting google drive to take excel sheet input
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [180]:
data = pd.read_csv('/content/gdrive/MyDrive/mpg.csv.zip')
data

mpg  cylinders  ...  origin                       name
0    18.0          8  ...       1  chevrolet chevelle malibu
1    15.0          8  ...       1          buick skylark 320
2    18.0          8  ...       1         plymouth satellite
3    16.0          8  ...       1              amc rebel sst
4    17.0          8  ...       1                ford torino
..    ...        ...  ...     ...                        ...
393  27.0          4  ...       1            ford mustang gl
394  44.0          4  ...       2                  vw pickup
395  32.0          4  ...       1              dodge rampage
396  28.0          4  ...       1                ford ranger
397  31.0          4  ...       1                 chevy s-10

[398 rows x 9 columns]

In [181]:
data.shape

(398, 9)

In [182]:
data.ndim         #dimension

2

In [183]:
data.head(n=7)

mpg  cylinders  displacement  ... model_year  origin                       name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite
3  16.0          8         304.0  ...         70       1              amc rebel sst
4  17.0          8         302.0  ...         70       1                ford torino
5  15.0          8         429.0  ...         70       1           ford galaxie 500
6  14.0          8         454.0  ...         70       1           chevrolet impala

[7 rows x 9 columns]

In [184]:
data.tail(n=7)

mpg  cylinders  displacement  ... model_year  origin               name
391  36.0          4         135.0  ...         82       1  dodge charger 2.2
392  27.0          4         151.0  ...         82       1   chevrolet camaro
393  27.0          4         140.0  ...         82       1    ford mustang gl
394  44.0          4          97.0  ...         82       2          vw pickup
395  32.0          4         135.0  ...         82       1      dodge rampage
396  28.0          4         120.0  ...         82       1        ford ranger
397  31.0          4         119.0  ...         82       1         chevy s-10

[7 rows x 9 columns]

In [185]:
data.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [186]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   name          398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [187]:
#here we see the horsepower being object but we know that it contains numerc values lets inspect

Continous Column -- Many values in column

Discreet Column -- Very very less values

In [188]:
data['origin'].unique()

array([1, 3, 2])

In [189]:
data['cylinders'].unique()      #discreet column

array([8, 4, 6, 3, 5])

In [190]:
data['displacement'].unique()     #continuous column

array([307. , 350. , 318. , 304. , 302. , 429. , 454. , 440. , 455. ,
       390. , 383. , 340. , 400. , 113. , 198. , 199. , 200. ,  97. ,
       110. , 107. , 104. , 121. , 360. , 140. ,  98. , 232. , 225. ,
       250. , 351. , 258. , 122. , 116. ,  79. ,  88. ,  71. ,  72. ,
        91. ,  97.5,  70. , 120. ,  96. , 108. , 155. ,  68. , 114. ,
       156. ,  76. ,  83. ,  90. , 231. , 262. , 134. , 119. , 171. ,
       115. , 101. , 305. ,  85. , 130. , 168. , 111. , 260. , 151. ,
       146. ,  80. ,  78. , 105. , 131. , 163. ,  89. , 267. ,  86. ,
       183. , 141. , 173. , 135. ,  81. , 100. , 145. , 112. , 181. ,
       144. ])

In [191]:
data['mpg'].unique()           #continuous column

array([18. , 15. , 16. , 17. , 14. , 24. , 22. , 21. , 27. , 26. , 25. ,
       10. , 11. ,  9. , 28. , 19. , 12. , 13. , 23. , 30. , 31. , 35. ,
       20. , 29. , 32. , 33. , 17.5, 15.5, 14.5, 22.5, 24.5, 18.5, 29.5,
       26.5, 16.5, 31.5, 36. , 25.5, 33.5, 20.5, 30.5, 21.5, 43.1, 36.1,
       32.8, 39.4, 19.9, 19.4, 20.2, 19.2, 25.1, 20.6, 20.8, 18.6, 18.1,
       17.7, 27.5, 27.2, 30.9, 21.1, 23.2, 23.8, 23.9, 20.3, 21.6, 16.2,
       19.8, 22.3, 17.6, 18.2, 16.9, 31.9, 34.1, 35.7, 27.4, 25.4, 34.2,
       34.5, 31.8, 37.3, 28.4, 28.8, 26.8, 41.5, 38.1, 32.1, 37.2, 26.4,
       24.3, 19.1, 34.3, 29.8, 31.3, 37. , 32.2, 46.6, 27.9, 40.8, 44.3,
       43.4, 36.4, 44.6, 40.9, 33.8, 32.7, 23.7, 23.6, 32.4, 26.6, 25.8,
       23.5, 39.1, 39. , 35.1, 32.3, 37.7, 34.7, 34.4, 29.9, 33.7, 32.9,
       31.6, 28.1, 30.7, 24.2, 22.4, 34. , 38. , 44. ])

In [192]:
data['horsepower'].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [193]:
data['cylinders'].value_counts()

4    204
8    103
6     84
3      4
5      3
Name: cylinders, dtype: int64

In [194]:
#To find highest frequency we'll use mode
data['cylinders'].mode()

0    4
dtype: int64

In [195]:
data['mpg'].describe()

count    398.000000
mean      23.514573
std        7.815984
min        9.000000
25%       17.500000
50%       23.000000
75%       29.000000
max       46.600000
Name: mpg, dtype: float64

In [196]:
data['mpg'].median()      #we can see median in describe output at 50% for mpg

23.0

In [197]:
data['mpg'].var()

61.089610774274405

In [198]:
# data['horsepower'].mean()     #giving error because some data entries have ? in them

In [199]:
data.describe()

mpg   cylinders  ...  model_year      origin
count  398.000000  398.000000  ...  398.000000  398.000000
mean    23.514573    5.454774  ...   76.010050    1.572864
std      7.815984    1.701004  ...    3.697627    0.802055
min      9.000000    3.000000  ...   70.000000    1.000000
25%     17.500000    4.000000  ...   73.000000    1.000000
50%     23.000000    4.000000  ...   76.000000    1.000000
75%     29.000000    8.000000  ...   79.000000    2.000000
max     46.600000    8.000000  ...   82.000000    3.000000

[8 rows x 7 columns]

In [200]:
data.horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [201]:
data = data[data.horsepower != "?"]       #removing the data having ?

In [202]:
data.shape      #6 rows has been removed

(392, 9)

In [203]:
data.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model_year        int64
origin            int64
name             object
dtype: object

In [204]:
data.horsepower = data.horsepower.astype("float")      #object type has been changed to float

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [205]:
data.dtypes    

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
name             object
dtype: object

In [206]:
data.corr()       #correlation btw them

mpg  cylinders  ...  model_year    origin
mpg           1.000000  -0.777618  ...    0.580541  0.565209
cylinders    -0.777618   1.000000  ...   -0.345647 -0.568932
displacement -0.805127   0.950823  ...   -0.369855 -0.614535
horsepower   -0.778427   0.842983  ...   -0.416361 -0.455171
weight       -0.832244   0.897527  ...   -0.309120 -0.585005
acceleration  0.423329  -0.504683  ...    0.290316  0.212746
model_year    0.580541  -0.345647  ...    1.000000  0.181528
origin        0.565209  -0.568932  ...    0.181528  1.000000

[8 rows x 8 columns]

In [207]:
data['mpg'].kurt()

-0.5159934946351457

In [208]:
from sklearn.metrics import mean_squared_error, r2_score

In [209]:
from sklearn.model_selection import train_test_split
df=data

In [210]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [211]:
df.corr()

mpg  cylinders  ...  model_year    origin
mpg           1.000000  -0.777618  ...    0.580541  0.565209
cylinders    -0.777618   1.000000  ...   -0.345647 -0.568932
displacement -0.805127   0.950823  ...   -0.369855 -0.614535
horsepower   -0.778427   0.842983  ...   -0.416361 -0.455171
weight       -0.832244   0.897527  ...   -0.309120 -0.585005
acceleration  0.423329  -0.504683  ...    0.290316  0.212746
model_year    0.580541  -0.345647  ...    1.000000  0.181528
origin        0.565209  -0.568932  ...    0.181528  1.000000

[8 rows x 8 columns]

In [212]:
training_features = [ 'acceleration','displacement','horsepower','origin','displacement','model_year']
#Wt and cylinders dropped because of high correlation with displacement above 0.9
#name is dropped

target = 'mpg'
X_train, X_test, Y_train, Y_test = train_test_split(df[training_features],
                                                    df[target],
                                                     test_size=0.10, random_state=33)
#,random_state=88) #train_size=0.89  (training data should always be above 70% but not more than 90%)
#,  #0.1 to 0.2
    #    #random state 1 to 10000

In [213]:
#no. of rows in training data

In [214]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=4,p=1,weights='distance')# p=1 or p = 2 #- 1 manhattan 2 euclidean
                                                                 #3rd parameter can be uniform or distance-- means more importance is given to points nearer one so here comes the notion of weights are inversely proportional to distance 


In [215]:
model.fit(X_train,Y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=4, p=1,
                    weights='distance')

In [216]:
predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

Mean squared error: 6.23
R Square score: 0.90
